export const styles = {
  page: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
    boxSizing: "border-box",
    fontFamily:
      "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif",
  },
  card: {
    width: "100%",
    maxWidth: 860,
    border: "1px solid",
    borderRadius: 20,
    padding: 28,
    boxSizing: "border-box",
    boxShadow: "0 18px 50px rgba(15, 23, 42, 0.12)",
  },
  headerRow: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 16,
    marginBottom: 24,
  },
  headerText: {
    flex: 1,
    minWidth: 0,
  },
  title: {
    margin: 0,
    fontSize: 32,
    lineHeight: 1.1,
    fontWeight: 800,
    textAlign: "left",
  },
  darkModeLabel: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 14,
    fontWeight: 600,
    whiteSpace: "nowrap",
    userSelect: "none",
  },
  field: {
    display: "block",
    marginBottom: 16,
  },
  label: {
    display: "block",
    marginBottom: 8,
    fontSize: 14,
    fontWeight: 700,
    textAlign: "left",
  },
  input: {
    width: "100%",
    height: 40,
    border: "1px solid",
    borderRadius: 10,
    padding: "0 12px",
    fontSize: 15,
    outline: "none",
    boxSizing: "border-box",
  },
  buttonRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
    marginTop: 8,
  },
  primaryButton: {
    border: 0,
    borderRadius: 10,
    padding: "10px 16px",
    fontSize: 15,
    fontWeight: 700,
  },
  secondaryButton: {
    background: "transparent",
    border: "1px solid",
    borderRadius: 10,
    padding: "9px 15px",
    fontSize: 15,
    fontWeight: 650,
  },
  dangerButton: {
    border: "1px solid",
    borderRadius: 10,
    padding: "9px 15px",
    fontSize: 15,
    fontWeight: 700,
    cursor: "pointer",
  },
  status: {
    margin: "18px 0 0",
    fontSize: 14,
    textAlign: "center",
  },
  error: {
    margin: "0 0 16px",
    color: "#dc2626",
    fontSize: 14,
    textAlign: "center",
  },
  errorPanel: {
    margin: "0 0 18px",
    border: "1px solid",
    borderRadius: 12,
    padding: 14,
  },
  errorPanelTitle: {
    margin: 0,
    fontSize: 16,
    fontWeight: 800,
    textAlign: "left",
  },
  errorPanelMessage: {
    margin: "8px 0 0",
    fontSize: 14,
    lineHeight: 1.5,
    textAlign: "left",
    overflowWrap: "anywhere",
  },
  errorDetails: {
    margin: "12px 0 0",
    border: "1px solid",
    borderRadius: 10,
    padding: 12,
    fontSize: 12,
    lineHeight: 1.5,
    whiteSpace: "pre-wrap",
    overflowX: "auto",
    overflowWrap: "anywhere",
    fontFamily:
      "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
  },
  resultBox: {
    marginTop: 24,
    border: "1px solid",
    borderRadius: 14,
    padding: 16,
  },
  resultTitle: {
    margin: 0,
    fontSize: 20,
    fontWeight: 800,
    textAlign: "left",
  },
  resultSummary: {
    margin: "8px 0 12px",
    fontSize: 14,
    textAlign: "left",
  },
  findingsList: {
    display: "grid",
    gap: 12,
  },
  findingCard: {
    border: "1px solid",
    borderRadius: 12,
    padding: 14,
  },
  findingHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 8,
  },
  groupTitleArea: {
    minWidth: 0,
    flex: 1,
  },
  badgeStack: {
    display: "flex",
    alignItems: "flex-end",
    gap: 6,
    flexDirection: "column",
  },
  findingAlgorithm: {
    fontSize: 16,
    lineHeight: 1.35,
    overflowWrap: "anywhere",
  },
  confidenceBadge: {
    border: "1px solid",
    borderRadius: 999,
    padding: "3px 8px",
    fontSize: 12,
    fontWeight: 800,
    textTransform: "uppercase",
    whiteSpace: "nowrap",
  },
  countBadge: {
    border: "1px solid",
    borderRadius: 999,
    padding: "3px 8px",
    fontSize: 12,
    fontWeight: 800,
    whiteSpace: "nowrap",
  },
  findingInfo: {
    margin: 0,
    fontSize: 14,
    lineHeight: 1.5,
    overflowWrap: "anywhere",
    textAlign: "left",
    width: "100%",
  },
  findingMeta: {
    margin: "8px 0 0",
    fontSize: 12,
    lineHeight: 1.4,
    overflowWrap: "anywhere",
    textAlign: "left",
    fontFamily:
      "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
  },
  findingsDropdown: {
    marginTop: 12,
    border: "1px solid",
    borderRadius: 10,
    padding: 12,
  },
  findingsDropdownSummary: {
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 800,
    userSelect: "none",
    textAlign: "left",
  },
  locationList: {
    margin: "12px 0 0",
    paddingLeft: 20,
  },
  locationItem: {
    marginBottom: 8,
    paddingBottom: 8,
    borderBottom: "1px solid",
    fontSize: 12,
    lineHeight: 1.4,
    overflowWrap: "anywhere",
    textAlign: "left",
    fontFamily:
      "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
  },
  findingRowHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 6,
  },
  findingRowBadges: {
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "flex-end",
    gap: 6,
    flexWrap: "wrap",
  },
  findingRowTitle: {
    fontSize: 13,
    lineHeight: 1.35,
    overflowWrap: "anywhere",
    textAlign: "left",
    fontFamily:
      "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif",
  },
  findingRowMeta: {
    marginTop: 5,
    fontSize: 12,
    lineHeight: 1.4,
    overflowWrap: "anywhere",
    textAlign: "left",
  },
  locationMessage: {
    margin: "6px 0 0",
    fontSize: 12,
    lineHeight: 1.4,
    textAlign: "left",
    width: "100%",
    fontFamily:
      "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif",
  },
  innerDropdown: {
    marginTop: 10,
    border: "1px solid",
    borderRadius: 8,
    padding: 10,
  },
  innerDropdownSummary: {
    cursor: "pointer",
    fontSize: 12,
    fontWeight: 800,
    userSelect: "none",
    textAlign: "left",
  },
  referenceList: {
    margin: "8px 0 0",
    paddingLeft: 18,
  },
  referenceItem: {
    marginBottom: 6,
    fontSize: 12,
    lineHeight: 1.4,
    overflowWrap: "anywhere",
    textAlign: "left",
  },
};