server {
  listen 80;

  location / {
    if ($request_method = OPTIONS) {
      add_header Access-Control-Allow-Origin "http://localhost:8000" always;
      add_header Access-Control-Allow-Methods "GET, POST, OPTIONS" always;
      add_header Access-Control-Allow-Headers "Content-Type, Authorization" always;
      add_header Access-Control-Max-Age 86400 always;
      add_header Content-Length 0;
      add_header Content-Type text/plain;
      return 204;
    }

    add_header Access-Control-Allow-Origin "http://localhost:8000" always;
    add_header Access-Control-Allow-Methods "GET, POST, OPTIONS" always;
    add_header Access-Control-Allow-Headers "Content-Type, Authorization" always;

    proxy_pass http://opa-local:8181;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
  }
}